Repository Nexters/audy-client, pull requests merged in 2024-03, with the labels that each got.

#66 [AUD-107] 경로 소요시간 표출 기능 구현
  global.d.ts
  package.json
  pnpm-lock.yaml
  src/features/map/float-menu/FloatMenu.css.ts
  src/features/map/float-menu/FloatMenu.tsx
  src/utils/dayjs/index.ts
  src/utils/tmap/tmapModule.tsx
Labels: ✨ Feature

#63 [AUD-108] 코스 삭제 기능 구현
  src/apis/course/index.ts
  src/apis/course/type.ts
  src/components/pop-over/PopOverItem.tsx
  src/features/course/course-remove-modal/CourseRemoveModal.css.ts
  src/features/course/course-remove-modal/CourseRemoveModal.tsx
  src/features/course/course-remove-modal/index.ts
  src/features/course/course-tab/CourseTab.tsx
  src/features/course/course-tab/ThreeDotButton.tsx
  src/query-hooks/course/mutation.ts
Labels: ✨ Feature

#68 [AUD-121] 검색탭 핀 추가 버튼 기능 변경
  src/features/search/search-result-tab/SearchResultTab.css.ts
  src/features/search/search-result-tab/SearchResultTab.tsx
Labels: ✨ Feature

#69 [AUD-100] TmapModule 과 WebSocket 간의 기능 연동
  global.d.ts
  src/apis/course/type.ts
  src/features/map/float-menu/FloatMenu.tsx
  src/features/path/path-item/PathItem.tsx
  src/features/path/path-item/ThreeDotButton.tsx
  src/features/path/path-view/PathView.tsx
  src/features/search/search-result-tab/SearchResultTab.tsx
  src/features/search/search-results-container/SearchResultsContainer.tsx
  src/hooks/useSocket.ts
  src/hooks/useTmap.ts
  src/pages/course/CoursePage.tsx
  src/types/course.ts
  src/types/editor.ts
  src/types/map.ts
  src/utils/lexorank/index.ts
  src/utils/socket/StompProvider.tsx
  src/utils/tmap/TmapModuleProvider.tsx
  src/utils/tmap/tmapModule.tsx
Labels: 🔨 Refactor

#71 [HOTFIX] 최종 발표 시연 전 발생한 문제 해결
  src/apis/tmap/type.ts
  src/components/global-navigation-bar/GlobalNavigationBar.css.ts
  src/components/global-navigation-bar/GlobalNavigationBar.tsx
  src/features/map/float-menu/FloatMenu.tsx
  src/features/path/path-item/PathItem.tsx
  src/features/path/path-view/PathView.tsx
  src/features/search/search-result-tab/SearchResultTab.tsx
  src/query-hooks/user/query.ts
  src/types/course.ts
  src/types/editor.ts
  src/types/map.ts
  src/utils/tmap/tmapModule.tsx
Labels: 🐞 Bug
