Repository Nexters/audy-client, pull requests merged in 2024-01, with the labels that each got.

#1 [AUD-02] Vite 기반 프로젝트 세팅 및 라이브러리 설치
  .eslintrc.cjs
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/development.yml
  .gitignore
  .prettierrc.cjs
  README.md
  index.html
  package.json
  pnpm-lock.yaml
  public/vite.svg
  src/App.css
  src/App.tsx
  src/assets/react.svg
  src/index.css
  src/main.tsx
  src/styles/theme.css.ts
  src/types/global.d.ts
  src/vite-env.d.ts
  tsconfig.json
  tsconfig.node.json
  vite.config.ts
Labels: ⚙ Setting

#2 [AUD-10] 카카오 로그인 Redirection 구현
  package-lock.json
  src/App.tsx
  src/pages/LoginPage.tsx
  src/pages/RedirectionPage.tsx
Labels: ✨ Feature

#4 [AUD-7] T Map SDK 활용을 위한 TMapModule 및 useTMap Hook 제작
  .env.template
  .gitignore
  index.html
  package.json
  pnpm-lock.yaml
  src/App.tsx
  src/hooks/useTmap.ts
  src/main.tsx
  src/types/global.d.ts
  src/utils/tmap.ts
  tsconfig.json
Labels: ✨ Feature

#7 [AUD-17] API 공용 모듈 제작 및 React Query 세팅
  .env.template
  src/apis/api.ts
  src/main.tsx
Labels: ✨ Feature

#6 [AUD-16] react-router-dom createBrowserRouter 적용
  src/App.css
  src/App.tsx
  src/main.tsx
  src/pages/MainPage.tsx
  src/routes/index.tsx
Labels: ✨ Feature

#3 [AUD-11] 애플 로그인 Redirection 구현
  .gitignore
  src/constants/index.ts
  src/constants/login.ts
  src/pages/LoginPage.tsx
  src/pages/MainPage.tsx
  src/pages/RedirectionPage.tsx
  src/types/index.ts
  src/types/login.ts
  vite-env.d.ts
Labels: ✨ Feature

#5 [AUD-8] 마커 생성 및 삭제 기능 구현
  .env.template
  src/utils/tmap.ts
Labels: ✨ Feature

#9 [AUD-21] 검색 API 연동
  src/apis/search.ts
  src/types/index.ts
  src/types/search.ts
Labels: ✨ Feature

#8 [AUD-9] 시작과 종료 지점 간의 경로 그리기 기능 구현
  .env.template
  src/apis/tmap/index.ts
  src/apis/tmap/type.ts
  src/pages/LoginPage.tsx
  src/pages/MainPage.tsx
  src/utils/tmap.ts
Labels: ✨ Feature

#12 [AUD-23] globalStyle 및 Theme, Foundation 모듈 구현
  index.html
  package.json
  pnpm-lock.yaml
  public/fonts/Pretendard-Black.subset.woff2
  public/fonts/Pretendard-Bold.subset.woff2
  public/fonts/Pretendard-ExtraBold.subset.woff2
  public/fonts/Pretendard-Medium.subset.woff2
  public/fonts/Pretendard-Regular.subset.woff2
  public/fonts/Pretendard-SemiBold.subset.woff2
  src/index.css
  src/main.tsx
  src/pages/MainPage.tsx
  src/styles/foundation.ts
  src/styles/global.css.ts
  src/styles/theme.css.ts
  src/vite-env.d.ts
  vite-env.d.ts
  vite.config.ts
Labels: 🧑‍🎨 Style

#13 [AUD-3] 디자인 시스템 컬러 및 타이포 토큰 설정
  package.json
  pnpm-lock.yaml
  src/styles/foundation.ts
  src/styles/sprinkle.css.ts
  src/styles/theme.css.ts
Labels: 🧑‍🎨 Style

#14 [AUD-19] Global Navigation Bar 공용 컴포넌트 제작
  .env.template
  global.d.ts
  src/assets/icons/audyLogo.svg
  src/assets/icons/setting.svg
  src/assets/react.svg
  src/components/global-navigation-bar/GlobalNavigationBar.css.ts
  src/components/global-navigation-bar/GlobalNavigationBar.tsx
  src/components/global-navigation-bar/index.ts
  src/pages/MainPage.tsx
  src/styles/foundation.ts
  src/styles/sprinkle.css.ts
  src/vite-env.d.ts
  tsconfig.json
Labels: 🧑‍🎨 Style

#10 [AUD-24] infoWindow 생성 및 삭제 메서드 구현
  src/features/index.ts
  src/features/map/InfoWindow.tsx
  src/features/map/index.ts
  src/utils/tmap.ts
Labels: ✨ Feature

#11 [AUD-25] 지도 클릭 시 인포창 띄우는 기능 구현
  src/apis/tmap/index.ts
  src/apis/tmap/type.ts
  src/pages/MainPage.tsx
  src/utils/tmap.ts
Labels: ✨ Feature

#16 [AUD-26] 마커 클릭 시 인포창 뜨는 기능 구현
  package-lock.json
  src/features/map/InfoWindow.tsx
  src/types/map.ts
  src/utils/tmap.ts
Labels: ✨ Feature

#17 [AUD-28] infoWindow 리액트 컴포넌트로 변경 및 디자인 수정
  src/assets/icons/add.svg
  src/assets/icons/check.svg
  src/assets/icons/infoWindowLayout.svg
  src/assets/icons/location.svg
  src/features/index.ts
  src/features/map/InfoWindow.tsx
  src/features/map/info-window/InfoWindow.css.ts
  src/features/map/info-window/InfoWindow.tsx
  src/features/map/info-window/index.ts
  src/utils/tmap.tsx
Labels: 🧑‍🎨 Style

#19 [AUD-22] 코스 리스트 뷰 및 코스 아이템 컴포넌트 개발
  package.json
  pnpm-lock.yaml
  src/assets/icons/check.svg
  src/assets/icons/list.svg
  src/assets/icons/location.svg
  src/assets/icons/modify.svg
  src/assets/icons/trashCan.svg
  src/constants/dummy.ts
  src/features/course/course-item/CourseCheckBox.css.ts
  src/features/course/course-item/CourseCheckBox.tsx
  src/features/course/course-item/CourseControlBox.css.ts
  src/features/course/course-item/CourseControlBox.tsx
  src/features/course/course-item/CourseItem.css.ts
  src/features/course/course-item/CourseItem.tsx
  src/features/course/course-item/index.ts
  src/features/course/course-view/CourseView.css.ts
  src/features/course/course-view/CourseView.tsx
  src/features/course/course-view/CourseViewContextProvider.tsx
  src/features/course/course-view/index.ts
  src/hooks/useDisclosure.ts
  src/hooks/useOnClickOutside.ts
  src/pages/MainPage.tsx
Labels: ✨ Feature

#18 [AUD-29] 마커 추가 구현
  package-lock.json
  src/apis/tmap/index.ts
  src/apis/tmap/type.ts
  src/assets/icons/marker.svg
  src/components/global-navigation-bar/GlobalNavigationBar.tsx
  src/features/map/info-window/InfoWindow.css.ts
  src/features/map/info-window/InfoWindow.tsx
  src/features/map/marker/Marker.css.ts
  src/features/map/marker/Marker.tsx
  src/hooks/useTmap.ts
  src/pages/LoginPage.tsx
  src/pages/MainPage.tsx
  src/types/map.ts
  src/utils/tmap.tsx
Labels: ✨ Feature

#20 [AUD-32] 경로에 경유지 포함되지 않던 에러 해결
  src/apis/tmap/index.ts
  src/apis/tmap/type.ts
Labels: 🐞 Bug

#21 🐛 안쓰는 배열 주석처리
  src/utils/tmap.tsx
Labels: 🐞 Bug

#24 [AUD-33] 메인 페이지 퍼블리싱 및 지도 - 리스트 간 1차 연결 기능 추가
  global.d.ts
  src/assets/icons/leftArrow.svg
  src/assets/icons/modifyFilled.svg
  src/assets/icons/search.svg
  src/components/global-navigation-bar/GlobalNavigationBar.css.ts
  src/constants/dummy.ts
  src/features/course/course-item/CourseCheckBox.tsx
  src/features/course/course-item/CourseControlBox.tsx
  src/features/course/course-item/CourseItem.css.ts
  src/features/course/course-item/CourseItem.tsx
  src/features/course/course-view/CourseView.css.ts
  src/features/course/course-view/CourseView.tsx
  src/features/course/course-view/CourseViewContextProvider.tsx
  src/hooks/useEventListeners.ts
  src/hooks/useTmap.ts
  src/pages/MainPage.tsx
  src/pages/main/MainPage.css.ts
  src/pages/main/MainPage.tsx
  src/pages/main/index.ts
  src/routes/index.tsx
  src/styles/foundation.ts
  src/utils/tmap.tsx
Labels: ✨ Feature

#25 [AUD-31] 두 개의 Repository 를 하나로 통합하도록 로직 수정
  src/apis/search.ts
  src/apis/tmap/index.ts
  src/apis/tmap/type.ts
  src/features/course/course-item/CourseCheckBox.tsx
  src/features/course/course-item/CourseControlBox.tsx
  src/features/course/course-item/CourseItem.tsx
  src/features/course/course-view/CourseView.tsx
  src/hooks/useEventListeners.ts
  src/hooks/useOnClickOutside.ts
  src/hooks/useTmap.ts
  src/pages/main/MainPage.tsx
  src/types/search.ts
  src/utils/tmap.tsx
Labels: 🔨 Refactor

#27 [AUD-38] 지도 경로 표시 및 유형을 제어하는 FloatMenu 컴포넌트 추가
  global.d.ts
  src/apis/tmap/index.ts
  src/apis/tmap/type.ts
  src/features/course/course-view/CourseView.tsx
  src/features/map/float-menu/FloatMenu.css.ts
  src/features/map/float-menu/FloatMenu.tsx
  src/features/map/float-menu/index.ts
  src/hooks/useTmap.ts
  src/main.tsx
  src/pages/main/MainPage.css.ts
  src/pages/main/MainPage.tsx
  src/styles/foundation.ts
  src/types/map.ts
  src/utils/tmap/TmapModuleProvider.tsx
  src/utils/tmap/tmapModule.tsx
Labels: ✨ Feature

#15 [AUD-4] 프론트엔드 CI/CD 파이프라인 구축
  .github/workflows/production.yml
  src/types/index.ts
Labels: ⚙ Setting
