Repository Nexters/audy-client, pull requests merged in 2024-02, with the labels that each got.

#30 [AUD-50] 로그인 및 회원가입 페이지 퍼블리싱
  index.html
  public/icons/audyLogo.ico
  public/vite.svg
  src/assets/icons/appleLogo.svg
  src/assets/icons/kakaoLogo.svg
  src/assets/images/infoWindowLayout.svg
  src/constants/login.ts
  src/features/map/info-window/InfoWindow.tsx
  src/pages/LoginPage.tsx
  src/pages/auth/LoginPage.css.ts
  src/pages/auth/LoginPage.tsx
  src/pages/auth/index.ts
  src/routes/index.tsx
  src/types/login.ts
  src/vite-env.d.ts
Labels: 🧑‍🎨 Style

#31 [AUD-37] 마커 경로 그리기 기능 최적화
  global.d.ts
  src/features/course/course-item/CourseItem.tsx
  src/features/course/course-view/CourseView.tsx
  src/hooks/useDebounce.ts
  src/types/map.ts
  src/utils/tmap/tmapModule.tsx
Labels: 🔨 Refactor

#32 [AUD-55] 사이드 패널 공용 컴포넌트화
  src/apis/tmap/index.ts
  src/apis/tmap/type.ts
  src/components/side-panel/SidePanel.css.ts
  src/components/side-panel/SidePanel.tsx
  src/components/side-panel/index.ts
  src/constants/dummy.ts
  src/features/course/course-item/index.ts
  src/features/course/course-view/CourseViewContextProvider.tsx
  src/features/course/course-view/index.ts
  src/features/map/float-menu/FloatMenu.tsx
  src/features/path/path-item/PathCheckBox.css.ts
  src/features/path/path-item/PathCheckBox.tsx
  src/features/path/path-item/PathControlBox.css.ts
  src/features/path/path-item/PathControlBox.tsx
  src/features/path/path-item/PathItem.css.ts
  src/features/path/path-item/PathItem.tsx
  src/features/path/path-item/index.ts
  src/features/path/path-view/PathView.css.ts
  src/features/path/path-view/PathView.tsx
  src/features/path/path-view/PathViewContextProvider.tsx
  src/features/path/path-view/index.ts
  src/features/side-panel/SidePanel.tsx
  src/pages/course/CoursePage.css.ts
  src/pages/course/CoursePage.tsx
  src/pages/course/index.ts
  src/pages/main/MainPage.css.ts
  src/pages/main/MainPage.tsx
  src/pages/main/index.ts
  src/routes/index.tsx
  src/types/map.ts
  src/utils/tmap/tmapModule.tsx
Labels: 🔨 Refactor

#33 [AUD-58] 메인 페이지 레이아웃 퍼블리싱
  src/assets/icons/add.svg
  src/assets/icons/myCourse.svg
  src/assets/icons/person.svg
  src/assets/icons/pin.svg
  src/components/side-panel/SidePanel.css.ts
  src/features/course/course-filtering-tab/CourseFilteringTab.css.ts
  src/features/course/course-filtering-tab/CourseFilteringTab.tsx
  src/features/course/course-filtering-tab/index.ts
  src/features/course/course-tab/CourseTab.css.ts
  src/features/course/course-tab/CourseTab.tsx
  src/features/course/course-tab/index.ts
  src/features/course/courses-container/CoursesContainer.css.ts
  src/features/course/courses-container/CoursesContainer.tsx
  src/features/course/courses-container/index.ts
  src/features/map/info-window/InfoWindow.tsx
  src/features/search/search-result-tab/SearchResultTab.tsx
  src/pages/course/index.ts
  src/pages/main/MainPage.css.ts
  src/pages/main/MainPage.tsx
  src/pages/main/index.ts
  src/routes/index.tsx
  src/types/course.ts
  src/types/index.ts
Labels: 🧑‍🎨 Style

#37 [AUD-62] 검색으로 추가한 마커 에러 해결
  global.d.ts
  src/features/path/path-view/PathView.tsx
  src/features/search/search-result-tab/SearchResultTab.tsx
  src/features/search/search-result-tab/index.ts
  src/utils/tmap/tmapModule.tsx
Labels: 🐞 Bug

#36 [AUD-46] 코스 API Repository 및 Query Hook 제작
  src/apis/api.ts
  src/apis/course/index.ts
  src/apis/course/type.ts
  src/apis/tmap/index.ts
  src/apis/user/index.ts
  src/apis/user/type.ts
  src/features/search/search-bar/SearchBar.tsx
  src/query-hooks/course/key.ts
  src/query-hooks/course/mutation.ts
  src/query-hooks/course/query.ts
  src/query-hooks/user/key.ts
  src/query-hooks/user/query.ts
  src/types/auth.ts
  src/types/course.ts
  src/types/index.ts
  src/types/login.ts
  src/types/map.ts
  src/types/util.ts
  src/utils/tmap/tmapModule.tsx
Labels: ✨ Feature

#38 [AUD-66] useIntersectionObserver Hook 제작
  src/hooks/useIntersectionObserver.ts
Labels: ✨ Feature

#39 [AUD-69] socket 세팅
  package-lock.json
  package.json
  pnpm-lock.yaml
  src/hooks/useSocket.ts
Labels: ✨ Feature

#40 [AUD-72] 쓰리닷 UI 구현
  src/assets/icons/edit.svg
  src/assets/icons/eyeClosed.svg
  src/assets/icons/eyeOpened.svg
  src/assets/icons/threeDot.svg
  src/features/path/path-item/PathItem.css.ts
  src/features/path/path-item/PathItem.tsx
  src/features/path/path-item/ThreeDotButton.css.ts
  src/features/path/path-item/ThreeDotButton.tsx
  src/features/path/path-popover/PathPopover.css.ts
  src/features/path/path-popover/PathPopover.tsx
  src/features/path/path-popover/index.ts
  src/styles/foundation.ts
  src/types/map.ts
  src/utils/tmap/tmapModule.tsx
Labels: 🧑‍🎨 Style

#41 [AUD-70] 코스 목록 API 연동
  .env.template
  src/apis/api.ts
  src/components/async-boundary/AsyncBoundary.tsx
  src/components/async-boundary/index.ts
  src/constants/index.ts
  src/constants/login.ts
  src/features/course/course-tab/CourseTab.tsx
  src/features/course/courses-container/CoursesContainer.css.ts
  src/features/course/courses-container/CoursesContainer.tsx
  src/hooks/useIntersectionObserver.ts
  src/pages/login/LoginPage.tsx
  src/pages/main/MainPage.tsx
  src/query-hooks/course/query.ts
  src/query-hooks/user/query.ts
  src/routes/index.tsx
Labels: ✨ Feature

#44 [AUD-67] 코스 상세 정보 API 연동
  src/apis/tmap/index.ts
  src/apis/tmap/type.ts
  src/features/path/path-view/PathView.tsx
  src/main.tsx
  src/pages/course/CoursePage.loader.ts
  src/pages/course/CoursePage.tsx
  src/pages/course/index.ts
  src/query-hooks/course/query.ts
  src/query-hooks/search/key.ts
  src/query-hooks/search/query.ts
  src/routes/index.tsx
  src/utils/tmap/TmapModuleProvider.tsx
  src/utils/tmap/tmapModule.tsx
Labels: ✨ Feature

#47 [AUD-79] Tmap API 엔드포인트를 올바른 값으로 수정
  src/apis/tmap/index.ts
  src/hooks/useDebounce.ts
  src/hooks/useIntersectionObserver.ts
  src/styles/global.css.ts
  src/styles/theme.css.ts
  src/types/auth.ts
  src/types/course.ts
  src/types/util.ts
Labels: 🐞 Bug

#42 [AUD-71] 경로에서 숨김/표출 기능 구현
  src/assets/images/markerBlack.svg
  src/assets/images/markerWhite.svg
  src/features/map/marker/Marker.css.ts
  src/features/map/marker/Marker.tsx
  src/features/path/path-popover/PathPopover.tsx
  src/types/map.ts
  src/utils/tmap/tmapModule.tsx
Labels: ✨ Feature

#48 [AUD-82] AppPortal 유틸 공용 컴포넌트 제작
  src/components/app-portal/AppPortal.css.ts
  src/components/app-portal/AppPortal.tsx
  src/components/app-portal/index.ts
  src/routes/index.tsx
  src/styles/foundation.ts
Labels: ✨ Feature

#49 [AUD-84] StompJS 기반으로 WebSocket 구현체 변경
  package-lock.json
  package.json
  pnpm-lock.yaml
  src/apis/course/type.ts
  src/features/path/path-view/PathView.tsx
  src/hooks/useSocket.ts
Labels: 🔨 Refactor

#46 [AUD-77] 마커 클러스터링 기능 구현
  src/features/map/cluster/Cluster.css.ts
  src/features/map/cluster/Cluster.tsx
  src/features/map/cluster/index.ts
  src/features/map/marker/Marker.css.ts
  src/utils/tmap/ClusterModule.tsx
  src/utils/tmap/tmapModule.tsx
Labels: ✨ Feature

#50 [AUD-87] 툴팁 컴포넌트 구현
  src/assets/images/tail.svg
  src/components/tooltip/Tooltip.css.ts
  src/components/tooltip/Tooltip.tsx
  src/components/tooltip/index.ts
  src/styles/foundation.ts
Labels: 🧑‍🎨 Style

#43 [AUD-73] 토스트 컴포넌트 기능 구현
  src/components/toast/Toast.css.ts
  src/components/toast/Toast.tsx
  src/components/toast/index.ts
  src/hooks/useToast.ts
  src/routes/index.tsx
  src/styles/foundation.ts
  src/utils/toast/ToastProvider.tsx
Labels: ✨ Feature

#51 [AUD-78] 검색 API 연동 및 CoursePage 컴포넌트 구조 수정
  src/apis/course/index.ts
  src/apis/course/type.ts
  src/apis/tmap/index.ts
  src/features/course/course-name-input/CourseNameInput.css.ts
  src/features/course/course-name-input/CourseNameInput.tsx
  src/features/course/course-name-input/index.ts
  src/features/path/path-view/PathView.tsx
  src/features/search/search-bar/SearchBar.css.ts
  src/features/search/search-bar/SearchBar.tsx
  src/features/search/search-context/SearchContextProvider.tsx
  src/features/search/search-context/index.ts
  src/features/search/search-results-container/SearchResultsContainer.css.ts
  src/features/search/search-results-container/SearchResultsContainer.tsx
  src/pages/course/CoursePage.css.ts
  src/pages/course/CoursePage.tsx
  src/query-hooks/course/mutation.ts
  src/query-hooks/search/query.ts
Labels: ✨ Feature

#45 [AUD-75] 스낵바 공용 컴포넌트 기능 구현
  src/components/snack-bar/SnackBar.css.ts
  src/components/snack-bar/SnackBar.tsx
  src/components/snack-bar/index.ts
  src/hooks/useSnackBar.ts
  src/hooks/useToast.ts
  src/routes/index.tsx
  src/styles/foundation.ts
  src/utils/ui/SnackBarProvider.tsx
  src/utils/ui/ToastProvider.tsx
Labels: ✨ Feature

#55 [AUD-93] 에디터 프로필 컴포넌트 구현
  src/components/global-navigation-bar/GlobalNavigationBar.css.ts
  src/components/global-navigation-bar/GlobalNavigationBar.tsx
  src/features/user/editor-list/EditorList.css.ts
  src/features/user/editor-list/EditorList.tsx
  src/features/user/editor-list/index.ts
  src/features/user/editor-profile/EditorProfile.css.ts
  src/features/user/editor-profile/EditorProfile.tsx
  src/features/user/editor-profile/index.ts
Labels: 🧑‍🎨 Style

#53 [AUD-74] 토스트, 스낵바 스타일 변경
  src/assets/icons/close.svg
  src/components/snack-bar/SnackBar.css.ts
  src/components/snack-bar/SnackBar.tsx
  src/components/toast/Toast.css.ts
Labels: 🧑‍🎨 Style

#61 [AUD-105] 메인페이지에서 코스 진입 로직 추가
  src/components/pop-over/PopOverTrigger.tsx
  src/features/course/course-tab/CourseTab.css.ts
  src/features/course/course-tab/CourseTab.tsx
  src/features/course/courses-container/CoursesContainer.css.ts
  src/features/path/path-item/PathItem.css.ts
  src/features/path/path-view/PathView.css.ts
  src/features/search/search-result-tab/SearchResultTab.css.ts
  src/features/search/search-results-container/SearchResultsContainer.css.ts
Labels: ✨ Feature

#58 [AUD-81] 모달 공용 컴포넌트 개발 및 일부 적용
  package.json
  pnpm-lock.yaml
  src/components/global-navigation-bar/GlobalNavigationBar.tsx
  src/components/modal/Modal.css.ts
  src/components/modal/Modal.tsx
  src/components/modal/ModalContent.tsx
  src/components/modal/ModalFooter.tsx
  src/components/modal/ModalTitle.tsx
  src/components/modal/index.ts
  src/features/auth/sign-out-modal/SignOutModal.css.ts
  src/features/auth/sign-out-modal/SignOutModal.tsx
  src/features/auth/sign-out-modal/index.ts
  src/features/auth/withdraw-modal/WithdrawModal.css.ts
  src/features/auth/withdraw-modal/WithdrawModal.tsx
  src/features/auth/withdraw-modal/index.ts
  src/hooks/useModal.ts
  src/routes/index.tsx
  src/store/modal/action.ts
  src/store/modal/store.ts
  src/utils/ui/ModalProvider.tsx
Labels: ✨ Feature

#62 [AUD-111] 커스텀 에러 핸들러 추가
  src/apis/api.ts
  src/constants/status.ts
  src/utils/error/ApiError.ts
Labels: 🐞 Bug

#54 [AUD-92] 스낵바, 토스트 스택형태로 변경
  src/components/feedbacks-stack/FeedbacksStack.css.ts
  src/components/feedbacks-stack/FeedbacksStack.tsx
  src/components/feedbacks-stack/index.ts
  src/components/snack-bar/SnackBar.css.ts
  src/components/snack-bar/SnackBar.tsx
  src/components/toast/Toast.css.ts
  src/components/toast/Toast.tsx
  src/components/tooltip/TooltipTrigger.tsx
  src/hooks/useSnackBar.ts
  src/hooks/useToast.ts
  src/routes/index.tsx
  src/types/feedback.ts
  src/utils/ui/FeedbacksProvider.tsx
  src/utils/ui/SnackBarProvider.tsx
  src/utils/ui/ToastProvider.tsx
Labels: ✨ Feature

#59 [AUD-98] 유저 코스 초대 기능 구현
  src/apis/course/index.ts
  src/apis/editor/index.ts
  src/apis/editor/type.ts
  src/components/global-navigation-bar/GlobalNavigationBar.tsx
  src/components/modal/Modal.tsx
  src/features/user/editor-invite-modal/EditorInviteModal.css.ts
  src/features/user/editor-invite-modal/EditorInviteModal.tsx
  src/features/user/editor-invite-modal/index.ts
  src/features/user/editor-limit-modal/EditorLimitModal.css.ts
  src/features/user/editor-limit-modal/EditorLimitModal.tsx
  src/features/user/editor-limit-modal/index.ts
  src/features/user/editor-list/EditorList.tsx
  src/features/user/invalid-invite-modal/InvalidInviteModal.css.ts
  src/features/user/invalid-invite-modal/InvalidInviteModal.tsx
  src/features/user/invalid-invite-modal/index.ts
  src/pages/invite/InvitePage.css.ts
  src/pages/invite/InvitePage.loader.ts
  src/pages/invite/InvitePage.tsx
  src/pages/main/MainPage.tsx
  src/routes/index.tsx
  src/utils/ui/ModalProvider.tsx
Labels: ✨ Feature

#60 [AUD-102] 페이지 이동 시 지도 렌더링 안되는 문제 해결
  src/apis/course/index.ts
  src/pages/course/CoursePage.tsx
  src/utils/tmap/TmapModuleProvider.tsx
Labels: 🐞 Bug

#56 [AUD-95] 메인페이지 지도 클릭이벤트 막기
  src/pages/main/MainPage.tsx
Labels: ✨ Feature
